# Generated by Django 2.2 on 2019-05-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyticket',
            name='createTime',
            field=models.DateTimeField(null=True, verbose_name='购买车票日期'),
        ),
    ]
