# Generated by Django 2.2 on 2019-05-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsale', '0002_auto_20190509_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name_id',
            field=models.CharField(max_length=20, null=True, verbose_name='用户身份证'),
        ),
    ]
